# Generated by Django 2.0.6 on 2018-07-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('server', models.CharField(max_length=100)),
                ('crt_date', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField()),
                ('price', models.CharField(max_length=10)),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
    ]
